### ISSUE TITLE
Broken packer.io links

### ISSUE THREAD

**Issue by bendwyer** [hashicorp/packer-plugin-vagrant#20]
#### Overview of the Issue
https://www.packer.io/docs/builders/vagrant#template points to https://github.com/hashicorp/packer/blob/master/builder/vagrant/step_create_vagrantfile.go#L23-L37, which no longer exists in the `hashicorp/packer` repo resulting in a 404 error.

The file now resides in this repo at https://github.com/hashicorp/packer-plugin-vagrant/blob/main/builder/vagrant/step_create_vagrantfile.go

Additionally, attempting use the `Edit this page` link on the bottom of the page _also_ gives a 404 error. The old link points to https://github.com/hashicorp/packer/blob/master/website/content/docs/builders/vagrant.mdx which I guess also resides here now at https://github.com/hashicorp/packer-plugin-vagrant/blob/main/docs/builders/vagrant.mdx, but I'm not really sure if that is the correct file.

##### template
1. Navigate to https://www.packer.io/docs/builders/vagrant#template.
2. Click `here` link.

##### Edit this page
1. Navigate to https://www.packer.io/docs/builders/vagrant
2. Scroll to the bottom of the page.
3. Click `Edit this page` link on the right.

**Comment by VishnuJin** [comment]
I could not find `Edit this page` text in the entire document, is it valid now ?
